# Site Settings
title: 肖小粤
url: 'http://xiaoxiaoyue.me'
baseurl: '/resume' # change it according to your repository name（这里深坑，注意大小写）

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
# style: styles-3
# style: styles-4
# style: styles-5
# style: styles-6

# Profile information
name: 肖小粤
tagline: 不想搞区块链的后<br>端研发不是一个好<br>的机器学习工程师  # 少一点功利主义的追求<br>多一些不为什么的坚持
pic: profile.png
sex: 男
age: 1995.09.25
address: 广东省广州市

# Sidebar contact links
email: shawnyxiao@qq.com
# phone: 18588611169
website: xiaoxiaoyue.me  # do not add http://
github: ShawnyXiao

# Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
