# Site Settings
title: 肖小粤
url: 'http://shawnyxiao.github.io'
baseurl: '/resume' # change it according to your repository name（这里深坑，注意大小写）

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-1 # 青色-修订版1
style: styles-2 # 黑色-修订版2
# style: styles-3 # 绿色
# style: styles-4 # 紫色
# style: styles-5 # 橙色
# style: styles-6 # 灰色
# style: styles-7 # 蓝色

# Profile information
name: 肖小粤
tagline: 有上进心、完美主义者  # 少一点功利主义的追求<br>多一些不为什么的坚持
pic: profile.png
sex: 男
age: 1995.09.25
address: 广东省广州市

# Sidebar contact links
email: shawnyxiao@qq.com
# phone: 18588611169
website: shawnyxiao.github.io  # do not add http://
github: ShawnyXiao

# Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
